Repository cloudposse/terraform-example-module, pull requests merged in 2024-04, with the labels that each got.

#51 Add GitHub Settings
  .github/settings.yml
Labels: auto-update, no-release, migration

#57 New release workflows
  .github/auto-release.yml
  .github/workflows/feature-branch.yml
  .github/workflows/release-branch.yml
  .github/workflows/release-published.yml
Labels: needs-cloudposse

#59 Release published fix
  .github/workflows/release-published.yml
Labels: needs-cloudposse

#61 Update settings.yml
  .github/settings.yml
Labels: needs-cloudposse

#62 test-custom-branches-settings
  .github/settings.yml
Labels: needs-cloudposse

#63 Test different environment
  .github/settings.yml
Labels: needs-cloudposse

#64 test-relese2-env
  .github/settings.yml
Labels: needs-cloudposse

#66 Update settings.yml
  .github/settings.yml
Labels: needs-cloudposse

#67 Test release workflow
  main.tf
Labels: major

#68 Use GitHub Action Workflows from `cloudposse/.github` Repo
  .github/workflows/release-branch.yml
  .github/workflows/release-published.yml
Labels: auto-update, no-release, migration

#69 acceptance-test
  main.tf
Labels: major
